// Centralized UI strings. Keeping all copy in one place so a Thai translation
// (phase 3, via i18next) can be added later without touching components.
export const strings = {
  appName: 'MySync',

  nav: {
    dashboard: 'Dashboard',
    transactions: 'Records',
    debt: 'Debt',
    tax: 'Tax',
    settings: 'Settings',
  },

  common: {
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    optional: 'optional',
    all: 'All',
    none: 'None',
    today: 'Today',
  },

  dashboard: {
    title: 'This Month',
    income: 'Income',
    expense: 'Expense',
    balance: 'Balance',
    recent: 'Recent transactions',
    empty: 'No transactions yet. Tap + to add your first one.',
    topCategories: 'Top spending',
    spendingByCategory: 'Spending by category',
    quickAdd: 'Quick add',
    trackStocks: 'Track your stocks →',
    vsLastMonth: 'vs last month',
    noChange: 'no change',
    noExpenseData: 'No spending this month yet.',
  },

  tx: {
    income: 'Income',
    expense: 'Expense',
    amount: 'Amount',
    category: 'Category',
    tags: 'Tags',
    tagsHint: 'Comma separated, e.g. trip, work',
    newTag: 'New tag',
    noTagsHint: 'No tags yet. Tap Add to create one.',
    note: 'Note',
    date: 'Date',
    addTitle: 'Add transaction',
    editTitle: 'Edit transaction',
    deleteConfirm: 'Delete this transaction?',
    empty: 'No transactions.',
    pickCategory: 'Select a category',
    noResults: 'No transactions match your filters.',
  },

  filter: {
    search: 'Search',
    searchHint: 'Search note, tag or category',
    type: 'Type',
    allTypes: 'All',
    category: 'Category',
    allCategories: 'All categories',
    from: 'From',
    to: 'To',
    clear: 'Clear filters',
    filters: 'Filters',
    tagSummary: 'Totals by tag',
    resultCount: (n) => `${n} result${n === 1 ? '' : 's'}`,
  },

  tag: {
    title: 'Totals by tag',
    empty: 'No tags used yet. Add tags to transactions to see totals here.',
    spent: 'Spent',
    received: 'Received',
    count: (n) => `${n} item${n === 1 ? '' : 's'}`,
  },

  tagManage: {
    title: 'Manage tags',
    name: 'New tag name',
    empty: 'No tags yet. Create one below.',
    deleteConfirm: 'Delete this tag? Existing transactions keep the tag on their record.',
  },

  category: {
    manage: 'Manage categories',
    name: 'Category name',
    type: 'Type',
    both: 'Both',
    addTitle: 'Add category',
    deleteConfirm: 'Delete this category? Transactions using it will keep their record but show as uncategorized.',
    defaultBadge: 'default',
  },

  debt: {
    title: 'Debts',
    totalOutstanding: 'Total outstanding',
    dueSoon: 'Due soon',
    upcoming: 'Upcoming debts',
    paid: 'Paid',
    unpaid: 'Unpaid',
    markPaid: 'Mark as paid',
    markUnpaid: 'Mark as unpaid',
    addTitle: 'Add debt',
    editTitle: 'Edit debt',
    creditor: 'Creditor',
    creditorHint: 'e.g. KTC card, car loan',
    amount: 'Amount',
    dueDate: 'Due date',
    note: 'Note',
    empty: 'No debts. Tap + to add one.',
    deleteConfirm: 'Delete this debt?',
    overdue: 'Overdue',
    dueInDays: (n) => (n === 0 ? 'Due today' : `Due in ${n} day${n === 1 ? '' : 's'}`),
    allPaid: 'All debts paid. Nice!',
    showPaid: 'Show paid',
  },

  tax: {
    title: 'Tax Calculator',
    subtitle: 'Thai personal income tax (progressive)',
    annualIncome: 'Annual income',
    perYear: 'year',
    infoAria: 'How tax is calculated',
    extraDeductions: 'Extra deductions',
    extraHint: 'Insurance, RMF/SSF, donations, etc.',
    calculate: 'Calculate',
    result: 'Estimated tax',
    effectiveRate: 'Effective rate',
    afterTax: 'Income after tax',
    breakdownTitle: 'Deductions',
    personal: 'Personal allowance',
    expense: 'Expense deduction (50%, max 100k)',
    extra: 'Extra deductions',
    totalDeductions: 'Total deductions',
    taxableIncome: 'Taxable income',
    bracketsTitle: 'Tax by bracket',
    band: 'Band',
    rate: 'Rate',
    taxedAmount: 'Taxable',
    taxAmount: 'Tax',
    noTax: 'No tax due — taxable income is within the exempt band.',
    disclaimer:
      'Estimate only. Rates and allowances change yearly — verify with the Revenue Department. Not tax advice.',
  },

  // Educational content for the "i" info modal on the Tax page (Thai).
  taxInfo: {
    title: 'ภาษีเงินได้บุคคลธรรมดา (คร่าวๆ)',
    formulaTitle: 'คิดยังไง',
    formula: 'ไทยเก็บภาษีแบบขั้นบันได จาก "เงินได้สุทธิ" ไม่ใช่รายได้ทั้งก้อน',
    formulaLine: 'เงินได้สุทธิ = รายได้ทั้งปี − ค่าใช้จ่าย − ค่าลดหย่อน',
    bracketsTitle: 'อัตราขั้นบันได (คิดเฉพาะส่วนที่อยู่ในแต่ละช่วง)',
    thresholdTitle: 'รายได้เท่าไหร่เริ่มเสียภาษี',
    threshold:
      'ด้วยลดหย่อนพื้นฐาน (ค่าใช้จ่าย 50% สูงสุด 100,000 + ส่วนตัว 60,000) รายได้ประมาณ ≤ 25,800 บาท/เดือน (~310,000/ปี) มักไม่ต้องเสียภาษี ยิ่งมีลดหย่อนเพิ่มเพดานยิ่งสูงขึ้น แต่ถ้าเงินได้ทั้งปีเกิน 120,000 ยังต้อง "ยื่นแบบ" แม้ภาษีเป็นศูนย์',
    deductionsTitle: 'ค่าลดหย่อนที่เจอบ่อย',
    deductions:
      'นอกจากส่วนตัว 60,000: คู่สมรสไม่มีรายได้ 60,000, บุตร 30,000/คน, พ่อแม่ 30,000/คน, ประกันสังคม (สูงสุด ~9,000), ประกันชีวิต/สุขภาพ, กองทุน SSF/RMF/Thai ESG, ดอกเบี้ยบ้าน, เงินบริจาค ฯลฯ',
    otherIncomeTitle: 'รายได้อื่นนอกจากเงินเดือน',
    otherIncome:
      'โบนัสนับรวมเป็นเงินเดือน (หัก 50% เพดาน 100,000 เหมือนกัน) ส่วนค่าเช่า/ฟรีแลนซ์/ค้าขาย/วิชาชีพอิสระ หักค่าใช้จ่ายคนละเรต — เครื่องคิดเลขนี้ออกแบบสำหรับเงินเดือน+โบนัส ถ้ามีรายได้ประเภทอื่นตัวเลขจะเป็นค่าประเมินคร่าวๆ',
    usageTitle: 'วิธีใช้หน้านี้',
    usage:
      'ช่อง Annual income ใส่รายได้ทั้งปี (รวมโบนัส) | ช่อง Extra deductions ใส่ผลรวมลดหย่อนอื่นๆ ยกเว้นส่วนตัวกับค่าใช้จ่าย (แอพหักให้อัตโนมัติ) เช่น ประกันสังคม+ประกัน+SSF',
    disclaimer:
      'ข้อมูลนี้เป็นความรู้ทั่วไป ไม่ใช่คำแนะนำทางภาษี อัตรา/ค่าลดหย่อนเปลี่ยนได้ทุกปี ตรวจกับกรมสรรพากร (rd.go.th) ก่อนยื่นจริงเสมอ',
  },

  stock: {
    title: 'Investments',
    totalValue: 'Total value',
    today: 'Today',
    allGainLoss: 'Total gain/loss',
    addPortfolio: 'Add portfolio',
    editPortfolio: 'Edit portfolio',
    portfolioName: 'Portfolio name',
    portfolioNameHint: 'e.g. Long-term',
    note: 'Note',
    emptyPortfolios: 'No portfolios yet. Create one to start tracking your stocks.',
    deletePortfolioConfirm: 'Delete this portfolio and all of its holdings?',
    positions: (n) => `${n} position${n === 1 ? '' : 's'}`,

    holdings: 'Holdings',
    addHolding: 'Add holding',
    editHolding: 'Edit holding',
    symbol: 'Symbol',
    symbolHint: 'e.g. AAPL, or PTT.BK for Thai',
    shares: 'Shares',
    avgCost: 'Avg cost / share',
    currency: 'Currency',
    deleteHoldingConfirm: 'Delete this holding?',
    emptyHoldings: 'No holdings yet. Tap + to add one.',

    refresh: 'Refresh',
    refreshing: 'Refreshing…',
    price: 'Price',
    value: 'Value',
    cost: 'Cost',
    updated: 'Updated',
    notFetched: 'Price not fetched yet',
    noKey: 'Add your stock API key in Settings to fetch live prices.',
    fetchError: 'Could not fetch some prices — check the symbol or your API key.',
    thaiHint: 'Thai (SET) symbols use a .BK suffix and may have limited free coverage.',
  },

  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    darkMode: 'Dark mode',
    hideBalances: 'Hide balances',
    data: 'Data',
    exportExcel: 'Export to Excel',
    exportCsv: 'Export to CSV',
    importFile: 'Import from file',
    importHint: 'Import a previously exported .xlsx or .csv backup.',
    importDone: 'Import complete.',
    importError: 'Could not read that file. Make sure it is a MySync export.',
    lastBackup: 'Last backup',
    never: 'never',
    about: 'About',
    aboutText: 'MySync keeps all your data on this device only. Back up regularly via export.',
    stocks: 'Stocks',
    stockApiKey: 'Stock API key',
    stockApiKeyHint:
      'Prices use your own free API key, stored on this device only. Get a free key, then paste it here.',
    getFreeKey: 'Get a free key',
    provider: 'Provider',
    saved: 'Saved',
  },
}
