// Centralized UI strings. Keeping all copy in one place so a Thai translation
// (phase 3, via i18next) can be added later without touching components.
export const strings = {
  appName: 'MySync',

  nav: {
    dashboard: 'Dashboard',
    transactions: 'Records',
    debt: 'Debt',
    tax: 'Tax',
    settings: 'Settings',
  },

  common: {
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    optional: 'optional',
    all: 'All',
    none: 'None',
    today: 'Today',
  },

  dashboard: {
    title: 'This Month',
    income: 'Income',
    expense: 'Expense',
    balance: 'Balance',
    recent: 'Recent transactions',
    empty: 'No transactions yet. Tap + to add your first one.',
    topCategories: 'Top spending',
    spendingByCategory: 'Spending by category',
    quickAdd: 'Quick add',
    vsLastMonth: 'vs last month',
    noChange: 'no change',
    noExpenseData: 'No spending this month yet.',
  },

  tx: {
    income: 'Income',
    expense: 'Expense',
    amount: 'Amount',
    category: 'Category',
    tags: 'Tags',
    tagsHint: 'Comma separated, e.g. trip, work',
    newTag: 'New tag',
    noTagsHint: 'No tags yet. Tap Add to create one.',
    note: 'Note',
    date: 'Date',
    addTitle: 'Add transaction',
    editTitle: 'Edit transaction',
    deleteConfirm: 'Delete this transaction?',
    empty: 'No transactions.',
    pickCategory: 'Select a category',
    noResults: 'No transactions match your filters.',
  },

  filter: {
    search: 'Search',
    searchHint: 'Search note, tag or category',
    type: 'Type',
    allTypes: 'All',
    category: 'Category',
    allCategories: 'All categories',
    from: 'From',
    to: 'To',
    clear: 'Clear filters',
    filters: 'Filters',
    tagSummary: 'Totals by tag',
    resultCount: (n) => `${n} result${n === 1 ? '' : 's'}`,
  },

  tag: {
    title: 'Totals by tag',
    empty: 'No tags used yet. Add tags to transactions to see totals here.',
    spent: 'Spent',
    received: 'Received',
    count: (n) => `${n} item${n === 1 ? '' : 's'}`,
  },

  tagManage: {
    title: 'Manage tags',
    name: 'New tag name',
    empty: 'No tags yet. Create one below.',
    deleteConfirm: 'Delete this tag? Existing transactions keep the tag on their record.',
  },

  category: {
    manage: 'Manage categories',
    name: 'Category name',
    type: 'Type',
    both: 'Both',
    addTitle: 'Add category',
    deleteConfirm: 'Delete this category? Transactions using it will keep their record but show as uncategorized.',
    defaultBadge: 'default',
  },

  debt: {
    title: 'Debts',
    totalOutstanding: 'Total outstanding',
    dueSoon: 'Due soon',
    upcoming: 'Upcoming debts',
    paid: 'Paid',
    unpaid: 'Unpaid',
    markPaid: 'Mark as paid',
    markUnpaid: 'Mark as unpaid',
    addTitle: 'Add debt',
    editTitle: 'Edit debt',
    creditor: 'Creditor',
    creditorHint: 'e.g. KTC card, car loan',
    amount: 'Amount',
    dueDate: 'Due date',
    note: 'Note',
    empty: 'No debts. Tap + to add one.',
    deleteConfirm: 'Delete this debt?',
    overdue: 'Overdue',
    dueInDays: (n) => (n === 0 ? 'Due today' : `Due in ${n} day${n === 1 ? '' : 's'}`),
    allPaid: 'All debts paid. Nice!',
    showPaid: 'Show paid',
  },

  tax: {
    title: 'Tax Calculator',
    subtitle: 'Thai personal income tax (progressive)',
    annualIncome: 'Annual income',
    extraDeductions: 'Extra deductions',
    extraHint: 'Insurance, RMF/SSF, donations, etc.',
    calculate: 'Calculate',
    result: 'Estimated tax',
    effectiveRate: 'Effective rate',
    afterTax: 'Income after tax',
    breakdownTitle: 'Deductions',
    personal: 'Personal allowance',
    expense: 'Expense deduction (50%, max 100k)',
    extra: 'Extra deductions',
    totalDeductions: 'Total deductions',
    taxableIncome: 'Taxable income',
    bracketsTitle: 'Tax by bracket',
    band: 'Band',
    rate: 'Rate',
    taxedAmount: 'Taxable',
    taxAmount: 'Tax',
    noTax: 'No tax due — taxable income is within the exempt band.',
    disclaimer:
      'Estimate only. Rates and allowances change yearly — verify with the Revenue Department. Not tax advice.',
  },

  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    darkMode: 'Dark mode',
    hideBalances: 'Hide balances',
    data: 'Data',
    exportExcel: 'Export to Excel',
    exportCsv: 'Export to CSV',
    importFile: 'Import from file',
    importHint: 'Import a previously exported .xlsx or .csv backup.',
    importDone: 'Import complete.',
    importError: 'Could not read that file. Make sure it is a MySync export.',
    lastBackup: 'Last backup',
    never: 'never',
    about: 'About',
    aboutText: 'MySync keeps all your data on this device only. Back up regularly via export.',
  },
}
