// Centralized UI strings. Keeping all copy in one place so a Thai translation
// (phase 3, via i18next) can be added later without touching components.
export const strings = {
  appName: 'MySync',

  nav: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    settings: 'Settings',
  },

  common: {
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    optional: 'optional',
    all: 'All',
    none: 'None',
    today: 'Today',
  },

  dashboard: {
    title: 'This Month',
    income: 'Income',
    expense: 'Expense',
    balance: 'Balance',
    recent: 'Recent transactions',
    empty: 'No transactions yet. Tap + to add your first one.',
    topCategories: 'Top spending',
    spendingByCategory: 'Spending by category',
    quickAdd: 'Quick add',
    vsLastMonth: 'vs last month',
    noChange: 'no change',
    noExpenseData: 'No spending this month yet.',
  },

  tx: {
    income: 'Income',
    expense: 'Expense',
    amount: 'Amount',
    category: 'Category',
    tags: 'Tags',
    tagsHint: 'Comma separated, e.g. trip, work',
    newTag: 'New tag',
    noTagsHint: 'No tags yet. Tap Add to create one.',
    note: 'Note',
    date: 'Date',
    addTitle: 'Add transaction',
    editTitle: 'Edit transaction',
    deleteConfirm: 'Delete this transaction?',
    empty: 'No transactions.',
    pickCategory: 'Select a category',
    noResults: 'No transactions match your filters.',
  },

  filter: {
    search: 'Search',
    searchHint: 'Search note, tag or category',
    type: 'Type',
    allTypes: 'All',
    category: 'Category',
    allCategories: 'All categories',
    from: 'From',
    to: 'To',
    clear: 'Clear filters',
    filters: 'Filters',
    tagSummary: 'Totals by tag',
    resultCount: (n) => `${n} result${n === 1 ? '' : 's'}`,
  },

  tag: {
    title: 'Totals by tag',
    empty: 'No tags used yet. Add tags to transactions to see totals here.',
    spent: 'Spent',
    received: 'Received',
    count: (n) => `${n} item${n === 1 ? '' : 's'}`,
  },

  tagManage: {
    title: 'Manage tags',
    name: 'New tag name',
    empty: 'No tags yet. Create one below.',
    deleteConfirm: 'Delete this tag? Existing transactions keep the tag on their record.',
  },

  category: {
    manage: 'Manage categories',
    name: 'Category name',
    type: 'Type',
    both: 'Both',
    addTitle: 'Add category',
    deleteConfirm: 'Delete this category? Transactions using it will keep their record but show as uncategorized.',
    defaultBadge: 'default',
  },

  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    darkMode: 'Dark mode',
    hideBalances: 'Hide balances',
    data: 'Data',
    exportExcel: 'Export to Excel',
    exportCsv: 'Export to CSV',
    importFile: 'Import from file',
    importHint: 'Import a previously exported .xlsx or .csv backup.',
    importDone: 'Import complete.',
    importError: 'Could not read that file. Make sure it is a MySync export.',
    lastBackup: 'Last backup',
    never: 'never',
    about: 'About',
    aboutText: 'MySync keeps all your data on this device only. Back up regularly via export.',
  },
}
